# # Place the document option output: github_document in the header,
output: github_document 
# Install packages needed below
install.packages("rlang")
install.packages("ggplot2")
library(ggplot2)
install.packages("lubridate")
library(lubridate)

# Define working directory and create folders
setwd("~/Homework")
dir.create("HW1")
setwd("~/Homework/HW1")

# # a brief description of your past experiences, if any,
# # of using R, RStudio, R Markdown, Git, Github, ggplot2 and dplyr,;
# Limited experience.
# Coded in R a few years ago when participating in a fraud detection project for an insurance company
# Mainly coded in SAS and VBA in the last 10 years

# # a plot, using ggplot, of some aspect of a data-set. The data-set should be found on the web
# # (i.e. not one that is preloaded in R or in some package)
# # and you should document any steps taken in retrieving the data.
# Define the URL for the data (URL to the ZIP file online)
url <- "https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist.zip"
# Define where the filename for the downloaded file (in the working directory)
destfile <- "eurofxref-hist.zip"
# Download the file
download.file(url, destfile)
# Unzip the file, and we will then have a CSV file in the directory
unzip("eurofxref-hist.zip")
# Import the CSV file to a dataset in R
eur <- read.csv("eurofxref-hist.csv")
# Filter only dates from this year
eur2 <- subset(eur,substr(Date,1,4)>=year(now()))
# Filter only dates from this month
eur3 <- subset(eur2,month(Date)>=month(now())-1)
# Plot the data using ggplot
ggplot(eur3, aes(y=USD, x=Date)) + geom_point()

# # End the document with a code chunk containing sessionInfo()
# # (see end of this document), informing the reader what versions of R and packages you are using.
sessionInfo()
